---
- name: Create AWS EC2 spot instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create spot instance
      ec2_instance:
        instance_type: t3.micro
        image:
          id: ami-0f3c7d07486cad139  # Specify AMI ID within the image dictionary
#        key_name: my_keypair
        region: us-east-1
        subnet_id: subnet-017ad3134d13bee7a  # Specify the subnet ID directly
        security_groups: sg-0b792d7d432d8d378  # Specify the security group ID directly
        spot_price: "0.005"  # Specify the spot price if needed
        spot_wait_timeout: 600  # Specify the wait timeout for spot instance provisioning
        spot_instance_type: "persistent"  # Set spot instance type to "persistent"
        spot_instance_interruption_behavior: "stop"  # Set instance interruption behavior to "stop"
        wait: yes
      register: ec2

    - debug:
        var: ec2.instances[0].public_dns_name
